# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tools.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'tools.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btools.proto\x12\x05tools\"\x1e\n\rStringRequest\x12\r\n\x05value\x18\x01 \x01(\t\"/\n\x0eStringResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2G\n\x0bGroqService\x12\x38\n\x07\x41skGroq\x12\x14.tools.StringRequest\x1a\x15.tools.StringResponse\"\x00\x32M\n\x0eWeatherService\x12;\n\nGetWeather\x12\x14.tools.StringRequest\x1a\x15.tools.StringResponse\"\x00\x32N\n\x10\x43\x61lculateService\x12:\n\tCalculate\x12\x14.tools.StringRequest\x1a\x15.tools.StringResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tools_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRINGREQUEST']._serialized_start=22
  _globals['_STRINGREQUEST']._serialized_end=52
  _globals['_STRINGRESPONSE']._serialized_start=54
  _globals['_STRINGRESPONSE']._serialized_end=101
  _globals['_GROQSERVICE']._serialized_start=103
  _globals['_GROQSERVICE']._serialized_end=174
  _globals['_WEATHERSERVICE']._serialized_start=176
  _globals['_WEATHERSERVICE']._serialized_end=253
  _globals['_CALCULATESERVICE']._serialized_start=255
  _globals['_CALCULATESERVICE']._serialized_end=333
# @@protoc_insertion_point(module_scope)
